server:
  port: 8080

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery.locator:
        enabled: false
        lowerCaseServiceId: true
# http://localhost:8080/dummy-educationservice/all -> http://localhost:8081/all
      routes:
        - id: eduid
          uri: lb://educationservice
          predicates:
            - Path= /dummy-educationservice/**
          filters:
            - RewritePath= /dummy-educationservice/(?<path>.*), /$\{path}

        - id: eduservice-clientid
          uri: lb://eduservice-client
          predicates:
            - Path= /dummy-eduservice-client/**
          filters:
            - RewritePath= /dummy-eduservice-client/(?<path>.*), /$\{path}
          #http://localhost:8080/dummy-eduservice-client/all



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
